#!/usr/bin/env bash
# Are the comments in English?
#
#   bash scripts/check-language.sh --comments=en  $(git diff --cached --name-only)
#   bash scripts/check-language.sh --comments=any $(git diff --cached --name-only)
#
# Why a script and not a convention: "we write in English here" holds while the three people who
# agreed to it are still around. This repository is public and expects contributors who never read
# the agreement, so the rule has to be something a machine says at the moment it is broken, rather
# than something a reviewer says a week later.
#
#   --comments=en    comments must be English too. The public engine.
#   --comments=any   comments in whatever the team speaks. A product repository with a Brazilian
#                    team is a legitimate case: the code travels, the reasoning stays with the
#                    people who wrote it.
#
# ⚠️ Built to be QUIET. A checker that flags every comment mentioning a foreign word flags English
# comments that are right, and is wrong on every hit. Two rules are baked in below:
#
#   1. A comment may QUOTE a foreign word in backticks while explaining it in English — "a key
#      spelled `nome`". Backtick content is stripped before anything is judged, or the checker
#      punishes the comments that do the most good.
#   2. One Portuguese-looking word means nothing; `senha`, `pessoa` and `pagina` can be a name, a
#      quote or an example. Only GRAMMAR words count, and only when TWO DIFFERENT ones show up in
#      the same comment. A Portuguese sentence has many. An English sentence quoting a Portuguese
#      word has one.
#
# A checker with false positives is a checker someone turns off, and then it protects nothing.
set -uo pipefail

COMMENTS=en
FILES=()
for arg in "$@"; do
  case "$arg" in
    --comments=*) COMMENTS="${arg#*=}" ;;
    *) FILES+=("$arg") ;;
  esac
done
[ "$COMMENTS" = any ] && exit 0
# No files is a MISTAKE, not a pass. The caller builds the list with a command substitution —
# `$(git ls-files '*.ts' '*.js' '*.sh')` — and when that comes back empty, because it ran outside
# the repository or with a pattern that matches nothing, exiting 0 would report a clean repository
# that had never been read. That is the most expensive mistake a check can make: the empty answer
# taken for a good one.
if [ ${#FILES[@]} -eq 0 ]; then
  echo "✗ no files to check — the list was empty."
  echo "  usage: bash scripts/check-language.sh --comments=en <file> [file ...]"
  echo "  CI builds the list with:  \$(git ls-files '*.ts' '*.js' '*.sh')"
  exit 2
fi

# Grammar words only. No nouns: a noun is how you get a false positive, because a noun can as easily
# be an identifier, a name or a quote.
GRAMMAR='não|nao|está|estão|estao|também|tambem|então|entao|porque|porém|porem|quando|onde|isso|isto|aquilo|dele|dela|deles|delas|pelo|pela|pelos|pelas|seu|sua|seus|suas|nosso|nossa|mesmo|mesma|outro|outra|aqui|ali|agora|depois|antes|sempre|nunca|talvez|ainda|já|mas|pois|assim|cada|todo|toda|todos|todas|muito|muita|pouco|pouca|qualquer|nenhum|nenhuma|algum|alguma|quem|cujo|cuja'

FAILURES=0
# Counted because the guard above only knows how MANY paths it was handed, not whether any of them
# existed. Run from a subdirectory — which is what `$(git ls-files …)` invites, since it prints
# paths from the repository root — every path misses, the loop skips them all, and a silent exit 0
# would say the tree was clean. The same empty answer, one level deeper.
READ=0

for f in "${FILES[@]}"; do
  [ -f "$f" ] || continue
  READ=$((READ + 1))
  case "$f" in
    # The bundle is generated by `npm run build:web`; minified React is nobody's prose. The name
    # here has to be the bundle's real one: a name that matches nothing leaves the skip dead.
    *node_modules/*|*panel-react.js|engine/web/generated/*) continue ;; # generated or vendored
    */locales/*) continue ;;                        # translations ARE other languages
    */cycle.json) continue ;;                       # state labels: data, not code
    # An example's PAGES are demonstration content — HTML written to be read, and the JSON that
    # configures it. Its scripts are not: `examples/template/checks/` ships real code an adopter
    # copies and runs, and a Portuguese comment there is as public as one in the engine. A glob
    # that skipped the whole folder would leave that code never read at all.
    *examples/*.html|*examples/*.json) continue ;;  # demonstration content, not engine
  esac
  case "$f" in
    *.ts|*.js|*.jsx|*.mjs|*.sh) ;;
    *) continue ;;
  esac

  # Comment lines only, with backtick content and quoted strings removed first.
  HITS=$(sed -E 's/`[^`]*`//g; s/"[^"]*"//g; '"s/'[^']*'//g" "$f" 2>/dev/null \
    | grep -nE '^[[:space:]]*(//|#|\*|/\*)' 2>/dev/null \
    | grep -iEc "($GRAMMAR)" 2>/dev/null || true)

  # Two DIFFERENT grammar words in the file's comments. One is an accident; two is a sentence.
  DISTINCT=$(sed -E 's/`[^`]*`//g; s/"[^"]*"//g; '"s/'[^']*'//g" "$f" 2>/dev/null \
    | grep -E '^[[:space:]]*(//|#|\*|/\*)' 2>/dev/null \
    | grep -ioE "\b($GRAMMAR)\b" 2>/dev/null | sort -u | wc -l)

  if [ "${DISTINCT:-0}" -ge 2 ]; then
    echo "  ✗ $f — the comments look like Portuguese ($DISTINCT grammar words)"
    sed -E 's/`[^`]*`//g' "$f" | grep -nE '^[[:space:]]*(//|#|\*|/\*)' \
      | grep -iE "\b($GRAMMAR)\b" | head -2 | sed 's/^/        /' | cut -c1-120
    FAILURES=$((FAILURES+1))
  fi
done

if [ $READ -eq 0 ]; then
  echo "✗ none of the ${#FILES[@]} path(s) could be opened — wrong directory?"
  echo "  the paths are read as given, and \$(git ls-files …) prints them from the repository root."
  exit 2
fi

if [ $FAILURES -gt 0 ]; then
  echo ""
  echo "  This repository is written in English, comments included. See CONTRIBUTING.md."
  echo "  A real exception goes in the exclusion list at the top of this script, with the reason."
  exit 1
fi
exit 0
